/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the make_jni_lists.py script.
 *
 * Copyright (C) 2009 Google Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define NO_IMPLICIT_ATOMICSTRING

#include "bindings/V8ArrayBufferView.cpp"
#include "bindings/V8CSSMediaRule.cpp"
#include "bindings/V8CSSStyleSheet.cpp"
#include "bindings/V8Counter.cpp"
#include "bindings/V8Event.cpp"
#include "bindings/V8Float32Array.cpp"
#include "bindings/V8HTMLDirectoryElement.cpp"
#include "bindings/V8HTMLKeygenElement.cpp"
#include "bindings/V8HTMLParagraphElement.cpp"
#include "bindings/V8HTMLParamElement.cpp"
#include "bindings/V8HashChangeEvent.cpp"
#include "bindings/V8History.cpp"
#include "bindings/V8RGBColor.cpp"
#include "bindings/V8TreeWalker.cpp"

#if ENABLE(FILE_SYSTEM)
#include "bindings/V8EntryArray.cpp"
#endif

#if ENABLE(GEOLOCATION)
#include "bindings/V8PositionErrorCallback.cpp"
#endif

#if ENABLE(INDEXED_DATABASE)
#include "bindings/V8IDBAny.cpp"
#endif

#if ENABLE(MEDIA_STREAM)
#include "bindings/V8MediaStreamList.cpp"
#include "bindings/V8PeerConnection.cpp"
#endif

#if ENABLE(SVG)
#include "bindings/V8SVGAnimatedAngle.cpp"
#include "bindings/V8SVGAnimatedEnumeration.cpp"
#include "bindings/V8SVGEllipseElement.cpp"
#include "bindings/V8SVGForeignObjectElement.cpp"
#include "bindings/V8SVGPathElement.cpp"
#include "bindings/V8SVGPathSegCurvetoCubicRel.cpp"
#include "bindings/V8SVGPathSegCurvetoQuadraticRel.cpp"
#endif

#if ENABLE(SVG) && ENABLE(FILTERS)
#include "bindings/V8SVGFEFuncBElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(SVG_FONTS)
#include "bindings/V8SVGFontFaceNameElement.cpp"
#endif

#if ENABLE(VIDEO)
#include "bindings/V8MediaError.cpp"
#endif

#if ENABLE(WEBGL)
#include "bindings/V8WebGLUniformLocation.cpp"
#endif

#if ENABLE(WEB_AUDIO)
#include "bindings/V8AudioParam.cpp"
#include "bindings/V8JavaScriptAudioNode.cpp"
#endif
