/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the make_jni_lists.py script.
 *
 * Copyright (C) 2009 Google Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define NO_IMPLICIT_ATOMICSTRING

#include "bindings/V8CSSImportRule.cpp"
#include "bindings/V8HTMLEmbedElement.cpp"
#include "bindings/V8Location.cpp"
#include "bindings/V8MediaQueryList.cpp"
#include "bindings/V8NodeList.cpp"
#include "bindings/V8WebKitAnimationList.cpp"
#include "bindings/V8WebKitCSSMatrix.cpp"
#include "bindings/V8XMLHttpRequest.cpp"

#if ENABLE(DATALIST)
#include "bindings/V8HTMLDataListElement.cpp"
#endif

#if ENABLE(DOM_STORAGE)
#include "bindings/V8Storage.cpp"
#endif

#if ENABLE(FILE_SYSTEM)
#include "bindings/V8FileSystemCallback.cpp"
#endif

#if ENABLE(NOTIFICATIONS)
#include "bindings/V8Notification.cpp"
#endif

#if ENABLE(SQL_DATABASE)
#include "bindings/V8SQLResultSetRowList.cpp"
#include "bindings/V8SQLTransaction.cpp"
#endif

#if ENABLE(SVG)
#include "bindings/V8SVGAnimatedBoolean.cpp"
#include "bindings/V8SVGPathSegCurvetoCubicAbs.cpp"
#include "bindings/V8SVGPoint.cpp"
#include "bindings/V8SVGPolylineElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(FILTERS)
#include "bindings/V8SVGFEGaussianBlurElement.cpp"
#include "bindings/V8SVGFETileElement.cpp"
#endif

#if ENABLE(TOUCH_EVENTS)
#include "bindings/V8TouchEvent.cpp"
#endif

#if ENABLE(WEB_AUDIO)
#include "bindings/V8ConvolverNode.cpp"
#include "bindings/V8RealtimeAnalyserNode.cpp"
#endif

#if ENABLE(XPATH)
#include "bindings/V8XPathEvaluator.cpp"
#endif
