/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the make_jni_lists.py script.
 *
 * Copyright (C) 2009 Google Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define NO_IMPLICIT_ATOMICSTRING

#include "bindings/V8CanvasRenderingContext2D.cpp"
#include "bindings/V8HTMLBodyElement.cpp"
#include "bindings/V8HTMLPreElement.cpp"
#include "bindings/V8Rect.cpp"
#include "bindings/V8Uint8Array.cpp"

#if ENABLE(BLOB) || ENABLE(FILE_SYSTEM)
#include "bindings/V8FileException.cpp"
#endif

#if ENABLE(DOM_STORAGE)
#include "bindings/V8StorageEvent.cpp"
#endif

#if ENABLE(FILE_SYSTEM)
#include "bindings/V8WebKitFlags.cpp"
#endif

#if ENABLE(INDEXED_DATABASE)
#include "bindings/V8IDBRequest.cpp"
#endif

#if ENABLE(SQL_DATABASE)
#include "bindings/V8SQLTransactionSyncCallback.cpp"
#endif

#if ENABLE(SVG)
#include "bindings/V8SVGAnimatedNumberList.cpp"
#include "bindings/V8SVGGradientElement.cpp"
#include "bindings/V8SVGPathSegLinetoVerticalRel.cpp"
#endif

#if ENABLE(SVG) && ENABLE(FILTERS)
#include "bindings/V8SVGFEDiffuseLightingElement.cpp"
#endif

#if ENABLE(WEBGL)
#include "bindings/V8OESStandardDerivatives.cpp"
#include "bindings/V8WebGLShader.cpp"
#endif

#if ENABLE(WEB_TIMING)
#include "bindings/V8PerformanceTiming.cpp"
#endif

#if ENABLE(XPATH)
#include "bindings/V8XPathNSResolver.cpp"
#endif
