/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the make_jni_lists.py script.
 *
 * Copyright (C) 2009 Google Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define NO_IMPLICIT_ATOMICSTRING

#include "bindings/V8CSSCharsetRule.cpp"
#include "bindings/V8CSSRuleList.cpp"
#include "bindings/V8ClientRectList.cpp"
#include "bindings/V8DOMStringMap.cpp"
#include "bindings/V8Element.cpp"
#include "bindings/V8HTMLAppletElement.cpp"
#include "bindings/V8HTMLDetailsElement.cpp"
#include "bindings/V8HTMLLinkElement.cpp"
#include "bindings/V8MemoryInfo.cpp"
#include "bindings/V8Text.cpp"

#if ENABLE(DEVICE_ORIENTATION)
#include "bindings/V8DeviceMotionEvent.cpp"
#endif

#if ENABLE(FILE_SYSTEM)
#include "bindings/V8ErrorCallback.cpp"
#endif

#if ENABLE(INSPECTOR)
#include "bindings/V8InjectedScriptHost.cpp"
#endif

#if ENABLE(SVG)
#include "bindings/V8SVGPathSegLinetoHorizontalRel.cpp"
#include "bindings/V8SVGPathSegMovetoAbs.cpp"
#endif

#if ENABLE(WEB_AUDIO)
#include "bindings/V8DynamicsCompressorNode.cpp"
#endif

#if ENABLE(WORKERS)
#include "bindings/V8WorkerNavigator.cpp"
#endif

#if ENABLE(XPATH)
#include "bindings/V8XPathExpression.cpp"
#endif
