/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the make_jni_lists.py script.
 *
 * Copyright (C) 2009 Google Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define NO_IMPLICIT_ATOMICSTRING

#include "bindings/V8CloseEvent.cpp"
#include "bindings/V8HTMLCanvasElement.cpp"
#include "bindings/V8HTMLCollection.cpp"
#include "bindings/V8HTMLDListElement.cpp"
#include "bindings/V8HTMLSelectElement.cpp"
#include "bindings/V8Range.cpp"
#include "bindings/V8StyleMedia.cpp"

#if ENABLE(FILE_SYSTEM)
#include "bindings/V8FileCallback.cpp"
#include "bindings/V8FileWriter.cpp"
#endif

#if ENABLE(GEOLOCATION)
#include "bindings/V8Geolocation.cpp"
#include "bindings/V8PositionCallback.cpp"
#endif

#if ENABLE(MEDIA_STREAM)
#include "bindings/V8MediaStreamTrack.cpp"
#include "bindings/V8NavigatorUserMediaError.cpp"
#include "bindings/V8SignalingCallback.cpp"
#endif

#if ENABLE(SQL_DATABASE)
#include "bindings/V8DatabaseSync.cpp"
#include "bindings/V8SQLResultSet.cpp"
#endif

#if ENABLE(SVG)
#include "bindings/V8SVGMaskElement.cpp"
#include "bindings/V8SVGPathSegArcAbs.cpp"
#include "bindings/V8SVGRect.cpp"
#include "bindings/V8SVGRenderingIntent.cpp"
#endif

#if ENABLE(SVG) && ENABLE(FILTERS)
#include "bindings/V8SVGFEDistantLightElement.cpp"
#endif

#if ENABLE(WEBGL)
#include "bindings/V8WebGLTexture.cpp"
#endif

#if ENABLE(WEB_AUDIO)
#include "bindings/V8OfflineAudioCompletionEvent.cpp"
#endif
