/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8CanvasRenderingContext2D.h"

#include "CanvasGradient.h"
#include "CanvasPattern.h"
#include "CanvasStyle.h"
#include "ExceptionCode.h"
#include "PlatformString.h"
#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingMacros.h"
#include "V8BindingState.h"
#include "V8CanvasGradient.h"
#include "V8CanvasPattern.h"
#include "V8CanvasRenderingContext.h"
#include "V8DOMWrapper.h"
#include "V8HTMLCanvasElement.h"
#include "V8HTMLImageElement.h"
#include "V8HTMLVideoElement.h"
#include "V8ImageData.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"
#include "V8TextMetrics.h"
#include <wtf/GetPtr.h>
#include <wtf/RefCounted.h>
#include <wtf/RefPtr.h>

namespace WebCore {

WrapperTypeInfo V8CanvasRenderingContext2D::info = { V8CanvasRenderingContext2D::GetTemplate, V8CanvasRenderingContext2D::derefObject, 0, &V8CanvasRenderingContext::info };

namespace CanvasRenderingContext2DInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> globalAlphaAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.globalAlpha._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8::Number::New(imp->globalAlpha());
}

static void globalAlphaAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.globalAlpha._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setGlobalAlpha(v);
    return;
}

static v8::Handle<v8::Value> globalCompositeOperationAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.globalCompositeOperation._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8String(imp->globalCompositeOperation());
}

static void globalCompositeOperationAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.globalCompositeOperation._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK_VOID(V8Parameter<WithNullCheck>, v, value);
    imp->setGlobalCompositeOperation(v);
    return;
}

static v8::Handle<v8::Value> lineWidthAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.lineWidth._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8::Number::New(imp->lineWidth());
}

static void lineWidthAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.lineWidth._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setLineWidth(v);
    return;
}

static v8::Handle<v8::Value> lineCapAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.lineCap._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8String(imp->lineCap());
}

static void lineCapAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.lineCap._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK_VOID(V8Parameter<WithNullCheck>, v, value);
    imp->setLineCap(v);
    return;
}

static v8::Handle<v8::Value> lineJoinAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.lineJoin._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8String(imp->lineJoin());
}

static void lineJoinAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.lineJoin._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK_VOID(V8Parameter<WithNullCheck>, v, value);
    imp->setLineJoin(v);
    return;
}

static v8::Handle<v8::Value> miterLimitAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.miterLimit._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8::Number::New(imp->miterLimit());
}

static void miterLimitAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.miterLimit._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setMiterLimit(v);
    return;
}

static v8::Handle<v8::Value> shadowOffsetXAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.shadowOffsetX._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8::Number::New(imp->shadowOffsetX());
}

static void shadowOffsetXAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.shadowOffsetX._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setShadowOffsetX(v);
    return;
}

static v8::Handle<v8::Value> shadowOffsetYAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.shadowOffsetY._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8::Number::New(imp->shadowOffsetY());
}

static void shadowOffsetYAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.shadowOffsetY._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setShadowOffsetY(v);
    return;
}

static v8::Handle<v8::Value> shadowBlurAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.shadowBlur._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8::Number::New(imp->shadowBlur());
}

static void shadowBlurAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.shadowBlur._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    float v = static_cast<float>(value->NumberValue());
    imp->setShadowBlur(v);
    return;
}

static v8::Handle<v8::Value> shadowColorAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.shadowColor._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8String(imp->shadowColor());
}

static void shadowColorAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.shadowColor._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK_VOID(V8Parameter<WithNullCheck>, v, value);
    imp->setShadowColor(v);
    return;
}

static v8::Handle<v8::Value> fontAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.font._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8String(imp->font());
}

static void fontAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.font._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK_VOID(V8Parameter<>, v, value);
    imp->setFont(v);
    return;
}

static v8::Handle<v8::Value> textAlignAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.textAlign._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8String(imp->textAlign());
}

static void textAlignAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.textAlign._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK_VOID(V8Parameter<>, v, value);
    imp->setTextAlign(v);
    return;
}

static v8::Handle<v8::Value> textBaselineAttrGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.textBaseline._get");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    return v8String(imp->textBaseline());
}

static void textBaselineAttrSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info)
{
    INC_STATS("DOM.CanvasRenderingContext2D.textBaseline._set");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(info.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK_VOID(V8Parameter<>, v, value);
    imp->setTextBaseline(v);
    return;
}

static v8::Handle<v8::Value> saveCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.save");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    imp->save();
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> restoreCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.restore");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    imp->restore();
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> scaleCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.scale");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, sx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    imp->scale(sx, sy);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> rotateCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.rotate");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, angle, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    imp->rotate(angle);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> translateCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.translate");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, tx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, ty, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    imp->translate(tx, ty);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> transformCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.transform");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, m11, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, m12, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, m21, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, m22, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 5, MissingIsUndefined)->NumberValue()));
    imp->transform(m11, m12, m21, m22, dx, dy);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setTransformCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setTransform");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, m11, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, m12, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, m21, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, m22, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 5, MissingIsUndefined)->NumberValue()));
    imp->setTransform(m11, m12, m21, m22, dx, dy);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> createLinearGradientCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.createLinearGradient");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(float, x0, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y0, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, x1, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y1, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    RefPtr<CanvasGradient> result = imp->createLinearGradient(x0, y0, x1, y1, ec);
    if (UNLIKELY(ec))
        goto fail;
    return toV8(result.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> createRadialGradientCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.createRadialGradient");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(float, x0, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y0, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, r0, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, x1, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y1, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, r1, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 5, MissingIsUndefined)->NumberValue()));
    RefPtr<CanvasGradient> result = imp->createRadialGradient(x0, y0, r0, x1, y1, r1, ec);
    if (UNLIKELY(ec))
        goto fail;
    return toV8(result.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> clearRectCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.clearRect");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, width, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, height, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    imp->clearRect(x, y, width, height);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> fillRectCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.fillRect");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, width, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, height, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    imp->fillRect(x, y, width, height);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> beginPathCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.beginPath");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    imp->beginPath();
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> closePathCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.closePath");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    imp->closePath();
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> moveToCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.moveTo");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    imp->moveTo(x, y);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> lineToCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.lineTo");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    imp->lineTo(x, y);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> quadraticCurveToCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.quadraticCurveTo");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, cpx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, cpy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    imp->quadraticCurveTo(cpx, cpy, x, y);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> bezierCurveToCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.bezierCurveTo");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, cp1x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, cp1y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, cp2x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, cp2y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 5, MissingIsUndefined)->NumberValue()));
    imp->bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x, y);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> arcToCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.arcTo");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(float, x1, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y1, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, x2, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y2, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, radius, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    imp->arcTo(x1, y1, x2, y2, radius, ec);
    if (UNLIKELY(ec))
        goto fail;
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> rectCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.rect");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, width, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, height, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    imp->rect(x, y, width, height);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> arcCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.arc");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, radius, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, startAngle, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, endAngle, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(bool, anticlockwise, MAYBE_MISSING_PARAMETER(args, 5, MissingIsUndefined)->BooleanValue());
    imp->arc(x, y, radius, startAngle, endAngle, anticlockwise, ec);
    if (UNLIKELY(ec))
        goto fail;
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> fillCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.fill");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    imp->fill();
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> strokeCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.stroke");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    imp->stroke();
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> clipCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.clip");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    imp->clip();
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> isPointInPathCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.isPointInPath");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    return v8Boolean(imp->isPointInPath(x, y));
}

static v8::Handle<v8::Value> measureTextCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.measureText");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<>, text, MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined));
    return toV8(imp->measureText(text));
}

static v8::Handle<v8::Value> setAlphaCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setAlpha");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, alpha, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    imp->setAlpha(alpha);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setCompositeOperationCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setCompositeOperation");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<>, compositeOperation, MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined));
    imp->setCompositeOperation(compositeOperation);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setLineWidthCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setLineWidth");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, width, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    imp->setLineWidth(width);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setLineCapCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setLineCap");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<>, cap, MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined));
    imp->setLineCap(cap);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setLineJoinCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setLineJoin");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<>, join, MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined));
    imp->setLineJoin(join);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setMiterLimitCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setMiterLimit");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, limit, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    imp->setMiterLimit(limit);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> clearShadowCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.clearShadow");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    imp->clearShadow();
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> fillTextCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.fillText");
    if (args.Length() < 3)
        return throwError("Not enough arguments", V8Proxy::TypeError);
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<>, text, MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined));
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 3) {
        imp->fillText(text, x, y);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, maxWidth, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    imp->fillText(text, x, y, maxWidth);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> strokeTextCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.strokeText");
    if (args.Length() < 3)
        return throwError("Not enough arguments", V8Proxy::TypeError);
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<>, text, MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined));
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 3) {
        imp->strokeText(text, x, y);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, maxWidth, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    imp->strokeText(text, x, y, maxWidth);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setStrokeColor1Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setStrokeColor1");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<>, color, MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined));
    if (args.Length() <= 1) {
        imp->setStrokeColor(color);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, alpha, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    imp->setStrokeColor(color, alpha);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setStrokeColor2Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setStrokeColor2");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, grayLevel, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 1) {
        imp->setStrokeColor(grayLevel);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, alpha, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    imp->setStrokeColor(grayLevel, alpha);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setStrokeColor3Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setStrokeColor3");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, r, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, g, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, b, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, a, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    imp->setStrokeColor(r, g, b, a);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setStrokeColor4Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setStrokeColor4");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, c, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, m, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, k, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, a, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    imp->setStrokeColor(c, m, y, k, a);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setStrokeColorCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setStrokeColor");
    if ((args.Length() == 1 && (args[0]->IsNull() || args[0]->IsUndefined() || args[0]->IsString() || args[0]->IsObject())) || (args.Length() == 2 && (args[0]->IsNull() || args[0]->IsUndefined() || args[0]->IsString() || args[0]->IsObject())))
        return setStrokeColor1Callback(args);
    if (args.Length() == 1 || args.Length() == 2)
        return setStrokeColor2Callback(args);
    if (args.Length() == 4)
        return setStrokeColor3Callback(args);
    if (args.Length() == 5)
        return setStrokeColor4Callback(args);
    V8Proxy::throwTypeError();
    return notHandledByInterceptor();
}

static v8::Handle<v8::Value> setFillColor1Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setFillColor1");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<>, color, MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined));
    if (args.Length() <= 1) {
        imp->setFillColor(color);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, alpha, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    imp->setFillColor(color, alpha);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setFillColor2Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setFillColor2");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, grayLevel, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 1) {
        imp->setFillColor(grayLevel);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, alpha, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    imp->setFillColor(grayLevel, alpha);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setFillColor3Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setFillColor3");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, r, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, g, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, b, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, a, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    imp->setFillColor(r, g, b, a);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setFillColor4Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setFillColor4");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, c, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, m, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, k, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, a, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    imp->setFillColor(c, m, y, k, a);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setFillColorCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setFillColor");
    if ((args.Length() == 1 && (args[0]->IsNull() || args[0]->IsUndefined() || args[0]->IsString() || args[0]->IsObject())) || (args.Length() == 2 && (args[0]->IsNull() || args[0]->IsUndefined() || args[0]->IsString() || args[0]->IsObject())))
        return setFillColor1Callback(args);
    if (args.Length() == 1 || args.Length() == 2)
        return setFillColor2Callback(args);
    if (args.Length() == 4)
        return setFillColor3Callback(args);
    if (args.Length() == 5)
        return setFillColor4Callback(args);
    V8Proxy::throwTypeError();
    return notHandledByInterceptor();
}

static v8::Handle<v8::Value> strokeRectCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.strokeRect");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, width, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, height, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 4) {
        imp->strokeRect(x, y, width, height);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, lineWidth, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    imp->strokeRect(x, y, width, height, lineWidth);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> drawImage1Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.drawImage1");
    if (args.Length() < 3)
        return throwError("Not enough arguments", V8Proxy::TypeError);
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(HTMLImageElement*, image, V8HTMLImageElement::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8HTMLImageElement::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    imp->drawImage(image, x, y, ec);
    if (UNLIKELY(ec))
        goto fail;
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> drawImage2Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.drawImage2");
    if (args.Length() < 5)
        return throwError("Not enough arguments", V8Proxy::TypeError);
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(HTMLImageElement*, image, V8HTMLImageElement::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8HTMLImageElement::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, width, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, height, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    imp->drawImage(image, x, y, width, height, ec);
    if (UNLIKELY(ec))
        goto fail;
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> drawImage3Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.drawImage3");
    if (args.Length() < 9)
        return throwError("Not enough arguments", V8Proxy::TypeError);
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(HTMLImageElement*, image, V8HTMLImageElement::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8HTMLImageElement::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    EXCEPTION_BLOCK(float, sx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sw, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sh, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 5, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 6, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dw, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 7, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dh, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 8, MissingIsUndefined)->NumberValue()));
    imp->drawImage(image, sx, sy, sw, sh, dx, dy, dw, dh, ec);
    if (UNLIKELY(ec))
        goto fail;
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> drawImage4Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.drawImage4");
    if (args.Length() < 3)
        return throwError("Not enough arguments", V8Proxy::TypeError);
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(HTMLCanvasElement*, canvas, V8HTMLCanvasElement::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8HTMLCanvasElement::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    imp->drawImage(canvas, x, y, ec);
    if (UNLIKELY(ec))
        goto fail;
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> drawImage5Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.drawImage5");
    if (args.Length() < 5)
        return throwError("Not enough arguments", V8Proxy::TypeError);
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(HTMLCanvasElement*, canvas, V8HTMLCanvasElement::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8HTMLCanvasElement::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, width, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, height, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    imp->drawImage(canvas, x, y, width, height, ec);
    if (UNLIKELY(ec))
        goto fail;
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> drawImage6Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.drawImage6");
    if (args.Length() < 9)
        return throwError("Not enough arguments", V8Proxy::TypeError);
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(HTMLCanvasElement*, canvas, V8HTMLCanvasElement::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8HTMLCanvasElement::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    EXCEPTION_BLOCK(float, sx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sw, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sh, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 5, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 6, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dw, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 7, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dh, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 8, MissingIsUndefined)->NumberValue()));
    imp->drawImage(canvas, sx, sy, sw, sh, dx, dy, dw, dh, ec);
    if (UNLIKELY(ec))
        goto fail;
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> drawImage7Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.drawImage7");
    if (args.Length() < 3)
        return throwError("Not enough arguments", V8Proxy::TypeError);
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(HTMLVideoElement*, video, V8HTMLVideoElement::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8HTMLVideoElement::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    imp->drawImage(video, x, y, ec);
    if (UNLIKELY(ec))
        goto fail;
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> drawImage8Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.drawImage8");
    if (args.Length() < 5)
        return throwError("Not enough arguments", V8Proxy::TypeError);
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(HTMLVideoElement*, video, V8HTMLVideoElement::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8HTMLVideoElement::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    EXCEPTION_BLOCK(float, x, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, width, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, height, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    imp->drawImage(video, x, y, width, height, ec);
    if (UNLIKELY(ec))
        goto fail;
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> drawImage9Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.drawImage9");
    if (args.Length() < 9)
        return throwError("Not enough arguments", V8Proxy::TypeError);
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(HTMLVideoElement*, video, V8HTMLVideoElement::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8HTMLVideoElement::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    EXCEPTION_BLOCK(float, sx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sw, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sh, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 5, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 6, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dw, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 7, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dh, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 8, MissingIsUndefined)->NumberValue()));
    imp->drawImage(video, sx, sy, sw, sh, dx, dy, dw, dh, ec);
    if (UNLIKELY(ec))
        goto fail;
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> drawImageCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.drawImage");
    if ((args.Length() == 3 && (args[0]->IsNull() || V8HTMLImageElement::HasInstance(args[0]))))
        return drawImage1Callback(args);
    if ((args.Length() == 5 && (args[0]->IsNull() || V8HTMLImageElement::HasInstance(args[0]))))
        return drawImage2Callback(args);
    if ((args.Length() == 9 && (args[0]->IsNull() || V8HTMLImageElement::HasInstance(args[0]))))
        return drawImage3Callback(args);
    if ((args.Length() == 3 && (args[0]->IsNull() || V8HTMLCanvasElement::HasInstance(args[0]))))
        return drawImage4Callback(args);
    if ((args.Length() == 5 && (args[0]->IsNull() || V8HTMLCanvasElement::HasInstance(args[0]))))
        return drawImage5Callback(args);
    if ((args.Length() == 9 && (args[0]->IsNull() || V8HTMLCanvasElement::HasInstance(args[0]))))
        return drawImage6Callback(args);
    if ((args.Length() == 3 && (args[0]->IsNull() || V8HTMLVideoElement::HasInstance(args[0]))))
        return drawImage7Callback(args);
    if ((args.Length() == 5 && (args[0]->IsNull() || V8HTMLVideoElement::HasInstance(args[0]))))
        return drawImage8Callback(args);
    if ((args.Length() == 9 && (args[0]->IsNull() || V8HTMLVideoElement::HasInstance(args[0]))))
        return drawImage9Callback(args);
    V8Proxy::throwTypeError();
    return notHandledByInterceptor();
}

static v8::Handle<v8::Value> drawImageFromRectCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.drawImageFromRect");
    if (args.Length() < 1)
        return throwError("Not enough arguments", V8Proxy::TypeError);
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(HTMLImageElement*, image, V8HTMLImageElement::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8HTMLImageElement::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    if (args.Length() <= 1) {
        imp->drawImageFromRect(image);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, sx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 2) {
        imp->drawImageFromRect(image, sx);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, sy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 3) {
        imp->drawImageFromRect(image, sx, sy);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, sw, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 4) {
        imp->drawImageFromRect(image, sx, sy, sw);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, sh, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 5) {
        imp->drawImageFromRect(image, sx, sy, sw, sh);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, dx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 5, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 6) {
        imp->drawImageFromRect(image, sx, sy, sw, sh, dx);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, dy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 6, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 7) {
        imp->drawImageFromRect(image, sx, sy, sw, sh, dx, dy);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, dw, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 7, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 8) {
        imp->drawImageFromRect(image, sx, sy, sw, sh, dx, dy, dw);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, dh, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 8, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 9) {
        imp->drawImageFromRect(image, sx, sy, sw, sh, dx, dy, dw, dh);
        return v8::Handle<v8::Value>();
    }
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<>, compositeOperation, MAYBE_MISSING_PARAMETER(args, 9, MissingIsUndefined));
    imp->drawImageFromRect(image, sx, sy, sw, sh, dx, dy, dw, dh, compositeOperation);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setShadow1Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setShadow1");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, width, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, height, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, blur, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 3) {
        imp->setShadow(width, height, blur);
        return v8::Handle<v8::Value>();
    }
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<>, color, MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined));
    if (args.Length() <= 4) {
        imp->setShadow(width, height, blur, color);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, alpha, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    imp->setShadow(width, height, blur, color, alpha);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setShadow2Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setShadow2");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, width, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, height, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, blur, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, grayLevel, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 4) {
        imp->setShadow(width, height, blur, grayLevel);
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, alpha, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    imp->setShadow(width, height, blur, grayLevel, alpha);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setShadow3Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setShadow3");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, width, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, height, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, blur, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, r, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, g, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, b, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 5, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, a, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 6, MissingIsUndefined)->NumberValue()));
    imp->setShadow(width, height, blur, r, g, b, a);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setShadow4Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setShadow4");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    EXCEPTION_BLOCK(float, width, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, height, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, blur, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, c, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, m, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, y, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 5, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, k, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 6, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, a, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 7, MissingIsUndefined)->NumberValue()));
    imp->setShadow(width, height, blur, c, m, y, k, a);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> setShadowCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.setShadow");
    if (args.Length() == 3 || (args.Length() == 4 && (args[3]->IsNull() || args[3]->IsUndefined() || args[3]->IsString() || args[3]->IsObject())) || (args.Length() == 5 && (args[3]->IsNull() || args[3]->IsUndefined() || args[3]->IsString() || args[3]->IsObject())))
        return setShadow1Callback(args);
    if (args.Length() == 4 || args.Length() == 5)
        return setShadow2Callback(args);
    if (args.Length() == 7)
        return setShadow3Callback(args);
    if (args.Length() == 8)
        return setShadow4Callback(args);
    V8Proxy::throwTypeError();
    return notHandledByInterceptor();
}

static v8::Handle<v8::Value> createPattern1Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.createPattern1");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(HTMLCanvasElement*, canvas, V8HTMLCanvasElement::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8HTMLCanvasElement::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<WithNullCheck>, repetitionType, MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined));
    RefPtr<CanvasPattern> result = imp->createPattern(canvas, repetitionType, ec);
    if (UNLIKELY(ec))
        goto fail;
    return toV8(result.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> createPattern2Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.createPattern2");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(HTMLImageElement*, image, V8HTMLImageElement::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8HTMLImageElement::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    STRING_TO_V8PARAMETER_EXCEPTION_BLOCK(V8Parameter<WithNullCheck>, repetitionType, MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined));
    RefPtr<CanvasPattern> result = imp->createPattern(image, repetitionType, ec);
    if (UNLIKELY(ec))
        goto fail;
    return toV8(result.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> createPatternCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.createPattern");
    if ((args.Length() == 2 && (args[0]->IsNull() || V8HTMLCanvasElement::HasInstance(args[0])) && (args[1]->IsNull() || args[1]->IsUndefined() || args[1]->IsString() || args[1]->IsObject())))
        return createPattern1Callback(args);
    if ((args.Length() == 2 && (args[0]->IsNull() || V8HTMLImageElement::HasInstance(args[0])) && (args[1]->IsNull() || args[1]->IsUndefined() || args[1]->IsString() || args[1]->IsObject())))
        return createPattern2Callback(args);
    V8Proxy::throwTypeError();
    return notHandledByInterceptor();
}

static v8::Handle<v8::Value> putImageDataCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.putImageData");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(ImageData*, imagedata, V8ImageData::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8ImageData::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    EXCEPTION_BLOCK(float, dx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    if (args.Length() <= 3) {
        imp->putImageData(imagedata, dx, dy, ec);
        if (UNLIKELY(ec))
            goto fail;
        return v8::Handle<v8::Value>();
    }
    EXCEPTION_BLOCK(float, dirtyX, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dirtyY, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 4, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dirtyWidth, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 5, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, dirtyHeight, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 6, MissingIsUndefined)->NumberValue()));
    imp->putImageData(imagedata, dx, dy, dirtyX, dirtyY, dirtyWidth, dirtyHeight, ec);
    if (UNLIKELY(ec))
        goto fail;
    return v8::Handle<v8::Value>();
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> createImageData1Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.createImageData1");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(ImageData*, imagedata, V8ImageData::HasInstance(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)) ? V8ImageData::toNative(v8::Handle<v8::Object>::Cast(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined))) : 0);
    RefPtr<ImageData> result = imp->createImageData(imagedata, ec);
    if (UNLIKELY(ec))
        goto fail;
    return toV8(result.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> createImageData2Callback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.createImageData2");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(float, sw, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sh, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    RefPtr<ImageData> result = imp->createImageData(sw, sh, ec);
    if (UNLIKELY(ec))
        goto fail;
    return toV8(result.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> createImageDataCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.createImageData");
    if ((args.Length() == 1 && (args[0]->IsNull() || V8ImageData::HasInstance(args[0]))))
        return createImageData1Callback(args);
    if (args.Length() == 2)
        return createImageData2Callback(args);
    V8Proxy::throwTypeError();
    return notHandledByInterceptor();
}

static v8::Handle<v8::Value> getImageDataCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.CanvasRenderingContext2D.getImageData");
    CanvasRenderingContext2D* imp = V8CanvasRenderingContext2D::toNative(args.Holder());
    ExceptionCode ec = 0;
    {
    EXCEPTION_BLOCK(float, sx, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sy, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 1, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sw, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 2, MissingIsUndefined)->NumberValue()));
    EXCEPTION_BLOCK(float, sh, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 3, MissingIsUndefined)->NumberValue()));
    RefPtr<ImageData> result = imp->getImageData(sx, sy, sw, sh, ec);
    if (UNLIKELY(ec))
        goto fail;
    return toV8(result.release());
    }
    fail:
    V8Proxy::setDOMException(ec);
    return v8::Handle<v8::Value>();
}

} // namespace CanvasRenderingContext2DInternal

static const BatchedAttribute CanvasRenderingContext2DAttrs[] = {
    // Attribute 'globalAlpha' (Type: 'attribute' ExtAttr: '')
    {"globalAlpha", CanvasRenderingContext2DInternal::globalAlphaAttrGetter, CanvasRenderingContext2DInternal::globalAlphaAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'globalCompositeOperation' (Type: 'attribute' ExtAttr: 'ConvertNullToNullString')
    {"globalCompositeOperation", CanvasRenderingContext2DInternal::globalCompositeOperationAttrGetter, CanvasRenderingContext2DInternal::globalCompositeOperationAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'lineWidth' (Type: 'attribute' ExtAttr: '')
    {"lineWidth", CanvasRenderingContext2DInternal::lineWidthAttrGetter, CanvasRenderingContext2DInternal::lineWidthAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'lineCap' (Type: 'attribute' ExtAttr: 'ConvertNullToNullString')
    {"lineCap", CanvasRenderingContext2DInternal::lineCapAttrGetter, CanvasRenderingContext2DInternal::lineCapAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'lineJoin' (Type: 'attribute' ExtAttr: 'ConvertNullToNullString')
    {"lineJoin", CanvasRenderingContext2DInternal::lineJoinAttrGetter, CanvasRenderingContext2DInternal::lineJoinAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'miterLimit' (Type: 'attribute' ExtAttr: '')
    {"miterLimit", CanvasRenderingContext2DInternal::miterLimitAttrGetter, CanvasRenderingContext2DInternal::miterLimitAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'shadowOffsetX' (Type: 'attribute' ExtAttr: '')
    {"shadowOffsetX", CanvasRenderingContext2DInternal::shadowOffsetXAttrGetter, CanvasRenderingContext2DInternal::shadowOffsetXAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'shadowOffsetY' (Type: 'attribute' ExtAttr: '')
    {"shadowOffsetY", CanvasRenderingContext2DInternal::shadowOffsetYAttrGetter, CanvasRenderingContext2DInternal::shadowOffsetYAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'shadowBlur' (Type: 'attribute' ExtAttr: '')
    {"shadowBlur", CanvasRenderingContext2DInternal::shadowBlurAttrGetter, CanvasRenderingContext2DInternal::shadowBlurAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'shadowColor' (Type: 'attribute' ExtAttr: 'ConvertNullToNullString')
    {"shadowColor", CanvasRenderingContext2DInternal::shadowColorAttrGetter, CanvasRenderingContext2DInternal::shadowColorAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'font' (Type: 'attribute' ExtAttr: '')
    {"font", CanvasRenderingContext2DInternal::fontAttrGetter, CanvasRenderingContext2DInternal::fontAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'textAlign' (Type: 'attribute' ExtAttr: '')
    {"textAlign", CanvasRenderingContext2DInternal::textAlignAttrGetter, CanvasRenderingContext2DInternal::textAlignAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'textBaseline' (Type: 'attribute' ExtAttr: '')
    {"textBaseline", CanvasRenderingContext2DInternal::textBaselineAttrGetter, CanvasRenderingContext2DInternal::textBaselineAttrSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'strokeStyle' (Type: 'attribute' ExtAttr: 'Custom')
    {"strokeStyle", V8CanvasRenderingContext2D::strokeStyleAccessorGetter, V8CanvasRenderingContext2D::strokeStyleAccessorSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
    // Attribute 'fillStyle' (Type: 'attribute' ExtAttr: 'Custom')
    {"fillStyle", V8CanvasRenderingContext2D::fillStyleAccessorGetter, V8CanvasRenderingContext2D::fillStyleAccessorSetter, 0 /* no data */, static_cast<v8::AccessControl>(v8::DEFAULT), static_cast<v8::PropertyAttribute>(v8::None), 0 /* on instance */},
};

static const BatchedCallback CanvasRenderingContext2DCallbacks[] = {
    {"save", CanvasRenderingContext2DInternal::saveCallback},
    {"restore", CanvasRenderingContext2DInternal::restoreCallback},
    {"scale", CanvasRenderingContext2DInternal::scaleCallback},
    {"rotate", CanvasRenderingContext2DInternal::rotateCallback},
    {"translate", CanvasRenderingContext2DInternal::translateCallback},
    {"transform", CanvasRenderingContext2DInternal::transformCallback},
    {"setTransform", CanvasRenderingContext2DInternal::setTransformCallback},
    {"createLinearGradient", CanvasRenderingContext2DInternal::createLinearGradientCallback},
    {"createRadialGradient", CanvasRenderingContext2DInternal::createRadialGradientCallback},
    {"clearRect", CanvasRenderingContext2DInternal::clearRectCallback},
    {"fillRect", CanvasRenderingContext2DInternal::fillRectCallback},
    {"beginPath", CanvasRenderingContext2DInternal::beginPathCallback},
    {"closePath", CanvasRenderingContext2DInternal::closePathCallback},
    {"moveTo", CanvasRenderingContext2DInternal::moveToCallback},
    {"lineTo", CanvasRenderingContext2DInternal::lineToCallback},
    {"quadraticCurveTo", CanvasRenderingContext2DInternal::quadraticCurveToCallback},
    {"bezierCurveTo", CanvasRenderingContext2DInternal::bezierCurveToCallback},
    {"arcTo", CanvasRenderingContext2DInternal::arcToCallback},
    {"rect", CanvasRenderingContext2DInternal::rectCallback},
    {"arc", CanvasRenderingContext2DInternal::arcCallback},
    {"fill", CanvasRenderingContext2DInternal::fillCallback},
    {"stroke", CanvasRenderingContext2DInternal::strokeCallback},
    {"clip", CanvasRenderingContext2DInternal::clipCallback},
    {"isPointInPath", CanvasRenderingContext2DInternal::isPointInPathCallback},
    {"measureText", CanvasRenderingContext2DInternal::measureTextCallback},
    {"setAlpha", CanvasRenderingContext2DInternal::setAlphaCallback},
    {"setCompositeOperation", CanvasRenderingContext2DInternal::setCompositeOperationCallback},
    {"setLineWidth", CanvasRenderingContext2DInternal::setLineWidthCallback},
    {"setLineCap", CanvasRenderingContext2DInternal::setLineCapCallback},
    {"setLineJoin", CanvasRenderingContext2DInternal::setLineJoinCallback},
    {"setMiterLimit", CanvasRenderingContext2DInternal::setMiterLimitCallback},
    {"clearShadow", CanvasRenderingContext2DInternal::clearShadowCallback},
    {"fillText", CanvasRenderingContext2DInternal::fillTextCallback},
    {"strokeText", CanvasRenderingContext2DInternal::strokeTextCallback},
    {"setStrokeColor", CanvasRenderingContext2DInternal::setStrokeColorCallback},
    {"setFillColor", CanvasRenderingContext2DInternal::setFillColorCallback},
    {"strokeRect", CanvasRenderingContext2DInternal::strokeRectCallback},
    {"drawImage", CanvasRenderingContext2DInternal::drawImageCallback},
    {"drawImageFromRect", CanvasRenderingContext2DInternal::drawImageFromRectCallback},
    {"setShadow", CanvasRenderingContext2DInternal::setShadowCallback},
    {"createPattern", CanvasRenderingContext2DInternal::createPatternCallback},
    {"putImageData", CanvasRenderingContext2DInternal::putImageDataCallback},
    {"createImageData", CanvasRenderingContext2DInternal::createImageDataCallback},
    {"getImageData", CanvasRenderingContext2DInternal::getImageDataCallback},
};

static v8::Persistent<v8::FunctionTemplate> ConfigureV8CanvasRenderingContext2DTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    desc->ReadOnlyPrototype();

    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "CanvasRenderingContext2D", V8CanvasRenderingContext::GetTemplate(), V8CanvasRenderingContext2D::internalFieldCount,
        CanvasRenderingContext2DAttrs, WTF_ARRAY_LENGTH(CanvasRenderingContext2DAttrs),
        CanvasRenderingContext2DCallbacks, WTF_ARRAY_LENGTH(CanvasRenderingContext2DCallbacks));
    v8::Local<v8::ObjectTemplate> instance = desc->InstanceTemplate();
    v8::Local<v8::ObjectTemplate> proto = desc->PrototypeTemplate();
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8CanvasRenderingContext2D::GetRawTemplate()
{
    V8BindingPerIsolateData* data = V8BindingPerIsolateData::current();
    V8BindingPerIsolateData::TemplateMap::iterator result = data->rawTemplateMap().find(&info);
    if (result != data->rawTemplateMap().end())
        return result->second;

    v8::HandleScope handleScope;
    v8::Persistent<v8::FunctionTemplate> templ = createRawTemplate();
    data->rawTemplateMap().add(&info, templ);
    return templ;
}

v8::Persistent<v8::FunctionTemplate> V8CanvasRenderingContext2D::GetTemplate()
{
    V8BindingPerIsolateData* data = V8BindingPerIsolateData::current();
    V8BindingPerIsolateData::TemplateMap::iterator result = data->templateMap().find(&info);
    if (result != data->templateMap().end())
        return result->second;

    v8::HandleScope handleScope;
    v8::Persistent<v8::FunctionTemplate> templ =
        ConfigureV8CanvasRenderingContext2DTemplate(GetRawTemplate());
    data->templateMap().add(&info, templ);
    return templ;
}

bool V8CanvasRenderingContext2D::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8CanvasRenderingContext2D::wrapSlow(CanvasRenderingContext2D* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    v8::Persistent<v8::Object> wrapperHandle = v8::Persistent<v8::Object>::New(wrapper);

    if (!hasDependentLifetime)
        wrapperHandle.MarkIndependent();
    getDOMObjectMap().set(impl, wrapperHandle);
    return wrapper;
}

void V8CanvasRenderingContext2D::derefObject(void* object)
{
    static_cast<CanvasRenderingContext2D*>(object)->deref();
}

} // namespace WebCore
