/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#include "config.h"
#include "V8ElementTimeControl.h"

#if ENABLE(SVG)

#include "ExceptionCode.h"
#include "RuntimeEnabledFeatures.h"
#include "V8Binding.h"
#include "V8BindingMacros.h"
#include "V8BindingState.h"
#include "V8DOMWrapper.h"
#include "V8IsolatedContext.h"
#include "V8Proxy.h"

namespace WebCore {

WrapperTypeInfo V8ElementTimeControl::info = { V8ElementTimeControl::GetTemplate, V8ElementTimeControl::derefObject, 0, 0 };

namespace ElementTimeControlInternal {

template <typename T> void V8_USE(T) { }

static v8::Handle<v8::Value> beginElementCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.ElementTimeControl.beginElement");
    ElementTimeControl* imp = V8ElementTimeControl::toNative(args.Holder());
    imp->beginElement();
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> beginElementAtCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.ElementTimeControl.beginElementAt");
    ElementTimeControl* imp = V8ElementTimeControl::toNative(args.Holder());
    EXCEPTION_BLOCK(float, offset, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    imp->beginElementAt(offset);
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> endElementCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.ElementTimeControl.endElement");
    ElementTimeControl* imp = V8ElementTimeControl::toNative(args.Holder());
    imp->endElement();
    return v8::Handle<v8::Value>();
}

static v8::Handle<v8::Value> endElementAtCallback(const v8::Arguments& args)
{
    INC_STATS("DOM.ElementTimeControl.endElementAt");
    ElementTimeControl* imp = V8ElementTimeControl::toNative(args.Holder());
    EXCEPTION_BLOCK(float, offset, static_cast<float>(MAYBE_MISSING_PARAMETER(args, 0, MissingIsUndefined)->NumberValue()));
    imp->endElementAt(offset);
    return v8::Handle<v8::Value>();
}

} // namespace ElementTimeControlInternal

static const BatchedCallback ElementTimeControlCallbacks[] = {
    {"beginElement", ElementTimeControlInternal::beginElementCallback},
    {"beginElementAt", ElementTimeControlInternal::beginElementAtCallback},
    {"endElement", ElementTimeControlInternal::endElementCallback},
    {"endElementAt", ElementTimeControlInternal::endElementAtCallback},
};

static v8::Persistent<v8::FunctionTemplate> ConfigureV8ElementTimeControlTemplate(v8::Persistent<v8::FunctionTemplate> desc)
{
    desc->ReadOnlyPrototype();

    v8::Local<v8::Signature> defaultSignature = configureTemplate(desc, "ElementTimeControl", v8::Persistent<v8::FunctionTemplate>(), V8ElementTimeControl::internalFieldCount,
        0, 0,
        ElementTimeControlCallbacks, WTF_ARRAY_LENGTH(ElementTimeControlCallbacks));
    v8::Local<v8::ObjectTemplate> instance = desc->InstanceTemplate();
    v8::Local<v8::ObjectTemplate> proto = desc->PrototypeTemplate();
    

    // Custom toString template
    desc->Set(getToStringName(), getToStringTemplate());
    return desc;
}

v8::Persistent<v8::FunctionTemplate> V8ElementTimeControl::GetRawTemplate()
{
    V8BindingPerIsolateData* data = V8BindingPerIsolateData::current();
    V8BindingPerIsolateData::TemplateMap::iterator result = data->rawTemplateMap().find(&info);
    if (result != data->rawTemplateMap().end())
        return result->second;

    v8::HandleScope handleScope;
    v8::Persistent<v8::FunctionTemplate> templ = createRawTemplate();
    data->rawTemplateMap().add(&info, templ);
    return templ;
}

v8::Persistent<v8::FunctionTemplate> V8ElementTimeControl::GetTemplate()
{
    V8BindingPerIsolateData* data = V8BindingPerIsolateData::current();
    V8BindingPerIsolateData::TemplateMap::iterator result = data->templateMap().find(&info);
    if (result != data->templateMap().end())
        return result->second;

    v8::HandleScope handleScope;
    v8::Persistent<v8::FunctionTemplate> templ =
        ConfigureV8ElementTimeControlTemplate(GetRawTemplate());
    data->templateMap().add(&info, templ);
    return templ;
}

bool V8ElementTimeControl::HasInstance(v8::Handle<v8::Value> value)
{
    return GetRawTemplate()->HasInstance(value);
}


v8::Handle<v8::Object> V8ElementTimeControl::wrapSlow(ElementTimeControl* impl)
{
    v8::Handle<v8::Object> wrapper;
    V8Proxy* proxy = 0;
    wrapper = V8DOMWrapper::instantiateV8Object(proxy, &info, impl);
    if (wrapper.IsEmpty())
        return wrapper;

    impl->ref();
    v8::Persistent<v8::Object> wrapperHandle = v8::Persistent<v8::Object>::New(wrapper);

    if (!hasDependentLifetime)
        wrapperHandle.MarkIndependent();
    getDOMObjectMap().set(impl, wrapperHandle);
    return wrapper;
}

void V8ElementTimeControl::derefObject(void* object)
{
    static_cast<ElementTimeControl*>(object)->deref();
}

} // namespace WebCore

#endif // ENABLE(SVG)
